apiVersion: v1
kind: PersistentVolume
metadata:
 name: cicdpv
 labels:
  app: nginx
spec:
  storageClassName: slow
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
  persistentVolumeReclaimPolicy: Delete
